databases:
  - name: postgres
    ipAllowList: []
    databaseName: taskbud
    user: taskbud

services:
  - type: web
    name: taskbud
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
